name: "pkl"
version: "0.1.5"
usage: "specify and validate values using pkl" 
description: "Wrapper around helm to use pkl instead of yaml for values"
ignoreFlags: false
platformCommand:
  - command: ${HELM_PLUGIN_DIR}/helm-pkl.sh
platformHooks:
  install:
    - command: chmod +x ${HELM_PLUGIN_DIR}/helm-pkl.sh

